language: rust

rust:
    - nightly
    - beta
    - stable

os:
    - linux
    - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

#env:
#    global:
#        - secure:

sudo: false

before_script:
- |
    pip install 'travis-cargo<0.2' --user
    export PATH=$HOME/.local/bin:$PATH

script:
    - rustc --version
    - cargo --version
    - cargo build --verbose
    - cargo test --verbose
    - cargo bench --verbose
    - cargo doc --verbose

after_success:
    - travis-cargo coveralls --no-sudo

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

#    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
