language: rust

rust:
  - "nightly"
  - "beta"
  - "stable"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

sudo: false

cache:
  directories:
    - $HOME/.ccache

cache: cargo

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=/usr/lib/ccache:$HOME/.local/bin:/Users/travis/Library/Python/2.7/bin:$PATH

script:
  - rustc --version
  - cargo --version
  - travis-cargo build
  - travis-cargo test
  - travis-cargo --only nightly bench
  - travis-cargo --only stable doc

  - if [ ${TRAVIS_OS_NAME} != "osx" ]; then travis-cargo coveralls --no-sudo --verify --exclude-pattern="test/,bench/,build/,target/"; fi; true
  - if [ ${TRAVIS_OS_NAME} != "osx" ]; then type ccache >/dev/null 2>&1 && ccache -s; fi; true

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
