language: rust

rust:
    - nightly
    - beta
    - stable

os:
    - linux
    - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

sudo: false

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:/Users/travis/Library/Python/2.7/bin:$PATH

script:
    - rustc --version
    - cargo --version
    - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only nightly bench &&
      travis-cargo --only stable doc

after_success:
    - |
      [ ${TRAVIS_OS_NAME} != "osx" ] && travis-cargo coveralls --no-sudo

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
