environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    RUSTVERSION: 1.4.0
  - TARGET: i686-pc-windows-msvc
    RUSTVERSION: 1.4.0
  - TARGET: i686-pc-windows-gnu
    RUSTVERSION: 1.4.0
  - TARGET: x86_64-pc-windows-msvc
    RUSTVERSION: nightly
  - TARGET: i686-pc-windows-msvc
    RUSTVERSION: nightly
  - TARGET: i686-pc-windows-gnu
    RUSTVERSION: nightly
  - TARGET: x86_64-pc-windows-msvc
    RUSTVERSION: beta
  - TARGET: i686-pc-windows-msvc
    RUSTVERSION: beta
  - TARGET: i686-pc-windows-gnu
    RUSTVERSION: beta

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUSTVERSION}-${env:TARGET}.exe"
  - rust-%RUSTVERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose
